### PR TITLE
Add support for RC 1.6

### PR DESCRIPTION
**Pull request by NotActuallyTerry**
This updates the variables supplied to match the new format (`smtp_host` instead of `smtp_server` + `smtp_port`)
There is also a crude translation included for all languages except for JP

### CODE REVIEW

**Comment by deflomu** [comment]
Hey, I do not use roundcube anymore and therefor cannot test thus. But I can add you as a maintainer to this repo if you want. Would you be interested?

**Comment by NotActuallyTerry** [comment]
Hey there! I would love to take over as maintainer

**Comment by HannesJo0139** [comment]
Really nice to have early beta support. However, this unfortunately breaks the plugin for stable 1.5. Maybe you could introduce separate branches or sth like that.

**Comment by NotActuallyTerry** [comment]
My bad, I've gone through and added tags to commits where I believe compatibility for RC versions ended. Those shoooooooooould sync across to packagist soon!

**Pull request merged**
